/* Lectern — exports: quiz results (Excel / printable PDF), attendance, annotated lesson PDF */
(function (H) {
  'use strict';
  const { t } = H;
  const safe = (s) => String(s || 'export').replace(/[\\/:*?"<>|]+/g, ' ').trim().slice(0, 60) || 'export';
  const optLetter = (i) => String.fromCharCode(65 + i);

  function answerText(q) {
    if (['mcq', 'tf'].includes(q.type) && q.options && q.options[q.correct] != null) return optLetter(q.correct) + '. ' + q.options[q.correct];
    return '';
  }

  H.exports = {
    async resultsXlsx(r) {
      if (!r) return;
      const X = await H.need.xlsx();
      const wb = X.utils.book_new();
      const head = ['Rank', 'Name', 'Score', 'Correct', 'Incorrect'].concat(r.questions.map((q, i) => 'Q' + (i + 1)));
      const rows = [head].concat(r.people.map((p) => [p.rank, p.name, p.score, p.correct, p.incorrect].concat(p.answers.map((a) => (a ? (a.ok === true ? '✓ ' : a.ok === false ? '✗ ' : '') + a.v + (a.score ? ` (+${a.score})` : '') : '')))));
      const ws = X.utils.aoa_to_sheet(rows);
      ws['!cols'] = head.map((c, i) => ({ wch: i === 1 ? 24 : i < 5 ? 9 : 22 }));
      X.utils.book_append_sheet(wb, ws, 'Results');
      const qrows = [['#', 'Type', 'Question', 'Correct answer', 'Responses', 'Average', 'Source']];
      r.questions.forEach((q, i) => {
        let resp = '';
        if (q.counts) resp = q.type === 'scale' ? q.counts.map((c, k) => `${k + 1}: ${c}`).join('  ') : q.options.map((o, k) => `${optLetter(k)}. ${o}: ${q.counts[k] || 0}`).join('  |  ');
        if (q.words) resp = q.words.join(', ');
        if (q.ideas) resp = q.ideas.map((x) => `${x.text} — ${x.by} (❤${x.reactions})`).join('  |  ');
        qrows.push([i + 1, q.type, q.text, answerText(q), resp, q.type === 'scale' ? (q.avg || 0).toFixed(2) : '', q.source || '']);
      });
      const qs = X.utils.aoa_to_sheet(qrows);
      qs['!cols'] = [{ wch: 4 }, { wch: 8 }, { wch: 50 }, { wch: 24 }, { wch: 70 }, { wch: 8 }, { wch: 24 }];
      X.utils.book_append_sheet(wb, qs, 'Questions');
      const info = X.utils.aoa_to_sheet([['Quiz', r.title], ['Subject', r.subject || ''], ['Lesson', r.lesson || ''], ['Date', new Date(r.at).toLocaleString()], ['Participants', r.people.length], ['Generated by', 'Lectern']]);
      info['!cols'] = [{ wch: 14 }, { wch: 50 }];
      X.utils.book_append_sheet(wb, info, 'Info');
      X.writeFile(wb, `${safe(r.title)} - results.xlsx`);
    },

    /** Opens the print dialog with a clean report — choose "Save as PDF". Works with Kurdish/Arabic text. */
    resultsPdf(r) {
      if (!r) return;
      const e = H.esc;
      const d = new Date(r.at);
      const medal = ['🥇', '🥈', '🥉'];
      const html = `<!doctype html><html><head><meta charset="utf-8"><title>${e(r.title)} - results</title><style>
        @page{size:A4;margin:14mm}body{font-family:"Segoe UI",Tahoma,"Noto Naskh Arabic",system-ui,sans-serif;color:#111827;font-size:12px}
        h1{font-size:22px;margin:0 0 4px}h2{font-size:15px;margin:22px 0 8px;border-bottom:2px solid #e5e7eb;padding-bottom:4px}
        .meta{color:#6b7280;margin-bottom:12px}.meta b{color:#111827}table{width:100%;border-collapse:collapse}
        th,td{border:1px solid #e5e7eb;padding:6px 8px;text-align:start;vertical-align:top}th{background:#f3f4f6}
        .lb{display:flex;gap:10px;flex-wrap:wrap}.lb div{border:1px solid #e5e7eb;border-radius:10px;padding:8px 12px;min-width:120px}
        .q{margin:8px 0;padding:8px 10px;border:1px solid #e5e7eb;border-radius:8px;page-break-inside:avoid}.ok{color:#059669;font-weight:600}
        .foot{margin-top:24px;color:#9ca3af;font-size:10px;text-align:center}[dir=auto]{unicode-bidi:plaintext}
      </style></head><body>
      <h1 dir="auto">${e(r.title)}</h1>
      <div class="meta">${r.subject ? `Subject: <b dir="auto">${e(r.subject)}</b> · ` : ''}Date: <b>${d.toLocaleDateString()}</b> · Time: <b>${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</b> · Participants: <b>${r.people.length}</b></div>
      <h2>🏆 Leaderboard</h2><div class="lb">${r.people.slice(0, 3).map((p, i) => `<div>${medal[i]} <b dir="auto">${e(p.name)}</b><br>${p.score} pts · ${p.correct} correct</div>`).join('') || 'No participants.'}</div>
      <h2>📊 Results</h2><table><tr><th>#</th><th>Name</th><th>Score</th><th>Correct</th><th>Incorrect</th><th>Note</th></tr>
      ${r.people.map((p) => `<tr><td>${p.rank}</td><td dir="auto">${e(p.emoji || '')} ${e(p.name)}</td><td>${p.score}</td><td>${p.correct}</td><td>${p.incorrect}</td><td></td></tr>`).join('')}</table>
      <h2>📋 Questions</h2>${r.questions.map((q, i) => `<div class="q"><b>${i + 1}.</b> <span dir="auto">${e(q.text)}</span>
        ${q.options && q.options.length && q.type !== 'scale' ? `<div>${q.options.map((o, k) => `<span class="${k === q.correct && q.type !== 'poll' ? 'ok' : ''}">${optLetter(k)}. <span dir="auto">${e(o)}</span>${q.counts ? ` (${q.counts[k] || 0})` : ''}</span>`).join(' &nbsp; ')}</div>` : ''}
        ${answerText(q) ? `<div class="ok">✓ Correct answer: <span dir="auto">${e(answerText(q))}</span></div>` : ''}
        ${q.type === 'scale' ? `<div>Average: <b>${(q.avg || 0).toFixed(2)}</b></div>` : ''}
        ${q.words ? `<div dir="auto">${e(q.words.join(', '))}</div>` : ''}
        ${q.ideas ? q.ideas.map((x) => `<div dir="auto">💡 ${e(x.text)} — <i>${e(x.by)}</i> (❤ ${x.reactions})</div>`).join('') : ''}
        ${q.source ? `<div style="color:#6b7280">📖 ${e(q.source)}</div>` : ''}</div>`).join('') || 'No questions.'}
      <div class="foot">Generated by Lectern</div></body></html>`;
      printHtml(html);
    },

    async attendanceXlsx(r) {
      const X = await H.need.xlsx();
      const rows = [['#', 'Name', 'Joined', 'Last seen', 'Still connected at export']].concat((r.people || []).map((p, i) => [i + 1, p.name, new Date(p.joinedAt).toLocaleTimeString(), p.lastSeen ? new Date(p.lastSeen).toLocaleTimeString() : '', p.online ? 'yes' : 'no']));
      const ws = X.utils.aoa_to_sheet([[r.title], ['Date', new Date(r.at).toLocaleString()], []].concat(rows));
      ws['!cols'] = [{ wch: 5 }, { wch: 28 }, { wch: 12 }, { wch: 12 }, { wch: 22 }];
      const wb = X.utils.book_new();
      X.utils.book_append_sheet(wb, ws, 'Attendance');
      X.writeFile(wb, `${safe(r.title)}.xlsx`);
    },

    /** Lesson with drawings → PDF file (one page per slide) */
    async lessonPdf(lesson) {
      H.toast(t('preparing'));
      const jsPDF = await H.need.jspdf();
      let pdf = null;
      for (const it of lesson.items) {
        const aspect = it.w && it.h ? it.w / it.h : 16 / 9;
        const W = 1600, Hh = Math.round(W / aspect);
        const c = document.createElement('canvas'); c.width = W; c.height = Hh;
        const x = c.getContext('2d');
        x.fillStyle = it.type === 'board' && it.bg === 'black' ? '#111' : '#fff'; x.fillRect(0, 0, W, Hh);
        if (it.type === 'image') {
          const u = await H.store.blobUrl(it.blobId);
          const img = new Image(); img.src = u;
          try { await img.decode(); x.drawImage(img, 0, 0, W, Hh); } catch (e) { /* skip broken image */ }
        } else if (it.type === 'board' && it.bg === 'grid') {
          x.strokeStyle = '#e5e7eb'; x.lineWidth = 1;
          for (let gx = 0; gx < W; gx += 40) { x.beginPath(); x.moveTo(gx, 0); x.lineTo(gx, Hh); x.stroke(); }
          for (let gy = 0; gy < Hh; gy += 40) { x.beginPath(); x.moveTo(0, gy); x.lineTo(W, gy); x.stroke(); }
        } else if (it.type !== 'board') {
          x.fillStyle = '#111827'; x.font = '600 54px "Segoe UI", system-ui, sans-serif'; x.textAlign = 'center';
          x.fillText(H.ui.typeIcon(it) + ' ' + (it.title || ''), W / 2, Hh / 2, W - 120);
          if (it.url) { x.font = '32px system-ui'; x.fillStyle = '#6b7280'; x.fillText(it.url, W / 2, Hh / 2 + 60, W - 120); }
        }
        const ops = (lesson.ink || {})[it.uid];
        if (ops && ops.length) ops.forEach((o) => H.ink.drawOp(x, o, W, Hh));
        const img = c.toDataURL('image/jpeg', 0.85);
        const pw = 297, ph = 297 / aspect;
        if (!pdf) pdf = new jsPDF({ orientation: pw >= ph ? 'landscape' : 'portrait', unit: 'mm', format: [pw, ph] });
        else pdf.addPage([pw, ph], pw >= ph ? 'landscape' : 'portrait');
        pdf.addImage(img, 'JPEG', 0, 0, pw, ph);
      }
      if (pdf) pdf.save(`${safe(lesson.title)}.pdf`);
    },
  };

  function printHtml(html) {
    const f = document.createElement('iframe');
    Object.assign(f.style, { position: 'fixed', right: 0, bottom: 0, width: 0, height: 0, border: 0 });
    document.body.appendChild(f);
    const d = f.contentWindow.document;
    d.open(); d.write(html); d.close();
    setTimeout(() => { f.contentWindow.focus(); f.contentWindow.print(); setTimeout(() => f.remove(), 60000); }, 350);
  }
})(window.Hub);
